# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-14 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=60)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('part', models.IntegerField(choices=[(0, 'Top Tenor'), (1, 'Second Tenor'), (2, 'Baritone'), (3, 'Bass')])),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('class_code', models.IntegerField(choices=[(0, '一般'), (1, '学生'), (2, '地方'), (3, '地方学生')])),
                ('permission', models.IntegerField(choices=[(0, '一般'), (1, '管理者'), (2, 'システム管理者')])),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '未割り当て'), (1, '割り当て済み'), (2, '販売済み')])),
                ('owner_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Member')),
            ],
        ),
    ]
